---
repos:
- repo: meta
  hooks:
  - id: check-hooks-apply

- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: python
    types: [python]
  - id: codespell
    name: codespell
    entry: codespell
    language: python
    types: [text]
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
  - id: flynt
    name: flynt
    entry: flynt
    language: python
    types: [python]
  - id: isort
    name: isort
    entry: isort
    language: python
    types: [python]
  - id: pytest
    name: pytest
    entry: pytest
    language: python
    types: [python]
  - id: pyupgrade
    name: pyupgrade
    entry: pyupgrade
    language: python
    types: [python]
