[tool.poetry]
name = "pynamodb-encoder"
version = "0.1.0"
description = "Helper classes that encode/decode pynamodb models to/from JSON serializable dict"
authors = ["Lin Yang <github@linyang.me>"]

[tool.poetry.dependencies]
python = "^3.9"
pynamodb = "^5.1.0"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
flake8 = "^4.0.1"
isort = "^5.10.1"
pyright = "^0.0.13"
pytest = "^6.2"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
